### ISSUE TITLE
Errors while installing Icefall in kaldilm | pip install -r requirements.txt 

### ISSUE THREAD

**Issue by chaksam** [csukuangfj/kaldilm#11]
pip install -r requirements.txt 
Collecting kaldilm
  Downloading kaldilm-1.8.tar.gz (48 kB)
     |████████████████████████████████| 48 kB 7.4 MB/s 
Collecting kaldialign
  Downloading kaldialign-0.2.tar.gz (39 kB)
Collecting sentencepiece>=0.1.96
  Downloading sentencepiece-0.1.96-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 10.8 MB/s 
Collecting tensorboard
  Downloading tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 10.6 MB/s 
Collecting requests<3,>=2.21.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting google-auth<2,>=1.6.3
  Downloading google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
     |████████████████████████████████| 152 kB 10.7 MB/s 
Requirement already satisfied: setuptools>=41.0.0 in /home/anaconda3/envs/k2/lib/python3.8/site-packages (from tensorboard->-r requirements.txt (line 4)) (57.4.0)
Collecting protobuf>=3.6.0
  Downloading protobuf-3.17.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 11.9 MB/s 
Collecting grpcio>=1.24.3
  Downloading grpcio-1.39.0-cp38-cp38-manylinux2014_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 11.9 MB/s 
Requirement already satisfied: wheel>=0.26 in /home/anaconda3/envs/k2/lib/python3.8/site-packages (from tensorboard->-r requirements.txt (line 4)) (0.37.0)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.4-py3-none-any.whl (97 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Requirement already satisfied: numpy>=1.12.0 in /home/anaconda3/envs/k2/lib/python3.8/site-packages (from tensorboard->-r requirements.txt (line 4)) (1.20.3)
Collecting absl-py>=0.4
  Using cached absl_py-0.13.0-py3-none-any.whl (132 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Requirement already satisfied: six in /home/anaconda3/envs/k2/lib/python3.8/site-packages (from absl-py>=0.4->tensorboard->-r requirements.txt (line 4)) (1.16.0)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)
Building wheels for collected packages: kaldilm, kaldialign
  Building wheel for kaldilm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/anaconda3/envs/k2/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-vrnivm7y
       cwd: /tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/__main__.py -> build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/__init__.py -> build/lib.linux-x86_64-3.8/kaldilm
  copying kaldilm/python/kaldilm/arpa2fst.py -> build/lib.linux-x86_64-3.8/kaldilm
  running build_ext
  sh: 1: cmake: not found
  make: *** No rule to make target '_kaldilm'.  Stop.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py", line 60, in <module>
      setuptools.setup(
    File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py", line 32, in build_extension
      raise Exception(
  Exception:
  Build kaldilm failed. Please check the error message.
  You can ask for help by creating an issue on GitHub.
  
  Click:
      https://github.com/csukuangfj/kaldilm/issues/new
  
  ----------------------------------------
  ERROR: Failed building wheel for kaldilm
  Running setup.py clean for kaldilm
  Building wheel for kaldialign (setup.py) ... done
  Created wheel for kaldialign: filename=kaldialign-0.2-cp38-cp38-linux_x86_64.whl size=189827 sha256=955f5b4e542d77bb66df4b2cb0ebdcb4d3effa1730b700f785072e3d709ebac0
  Stored in directory: /home/.cache/pip/wheels/cc/4e/da/ffc64af1d09024d85fa5231680b357945ad1461b3885aa4b93
Successfully built kaldialign
Failed to build kaldilm
Installing collected packages: urllib3, pyasn1, idna, charset-normalizer, certifi, rsa, requests, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, google-auth, werkzeug, tensorboard-plugin-wit, tensorboard-data-server, protobuf, markdown, grpcio, google-auth-oauthlib, absl-py, tensorboard, sentencepiece, kaldilm, kaldialign
    Running setup.py install for kaldilm ... error
    ERROR: Command errored out with exit status 1:
     command: /home/anaconda3/envs/k2/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kk8gof6e/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda3/envs/k2/include/python3.8/kaldilm
         cwd: /tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/
    Complete output (55 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/kaldilm
    copying kaldilm/python/kaldilm/__main__.py -> build/lib.linux-x86_64-3.8/kaldilm
    copying kaldilm/python/kaldilm/__init__.py -> build/lib.linux-x86_64-3.8/kaldilm
    copying kaldilm/python/kaldilm/arpa2fst.py -> build/lib.linux-x86_64-3.8/kaldilm
    running build_ext
    sh: 1: cmake: not found
    make: *** No rule to make target '_kaldilm'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py", line 60, in <module>
        setuptools.setup(
      File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/envs/k2/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/anaconda3/envs/k2/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py", line 32, in build_extension
        raise Exception(
    Exception:
    Build kaldilm failed. Please check the error message.
    You can ask for help by creating an issue on GitHub.
    
    Click:
        https://github.com/csukuangfj/kaldilm/issues/new
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/anaconda3/envs/k2/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ica4u958/kaldilm_72ebe56a74b840c68d19d09d0c4b74c5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kk8gof6e/install-record.txt --single-version-externally-managed --compile --install-headers /home/anaconda3/envs/k2/include/python3.8/kaldilm Check the logs for full command output.

**Comment by chaksam** [comment]
sudo apt-get install cmake

installing cmake resolved the issue

**Comment by huangruizhe** [comment]
@csukuangfj Hi, do you know if it is possible to use a lower version of CMake? I got this error:
``` 
CMake Error at CMakeLists.txt:12 (cmake_minimum_required):
CMake 3.8 or higher is required.  You are running version 3.7.2
```
I could not upgrade CMake easily on a server. Thanks in advance!

**Comment by csukuangfj** [comment]
Can you change https://github.com/csukuangfj/kaldilm/blob/f85108dbf5d506a0a2000d260fa403b1bc9dca85/CMakeLists.txt#L3

3.8 -> 3.7

However, I am not sure whether it works with CMake 3.7.

**Comment by csukuangfj** [comment]
CMake 3.11 and 3.18 are known to work.

Note: You don't need `root` permission to install CMake.

Just go to https://github.com/Kitware/CMake/releases and select a version you want to download, e.g., 

[cmake-3.22.0-rc2-linux-x86_64.sh](https://github.com/Kitware/CMake/releases/download/v3.22.0-rc2/cmake-3.22.0-rc2-linux-x86_64.sh)

After downloading, you can install it to a local dir and set `PATH` to point to the dir where `cmake` is installed.

**Comment by huangruizhe** [comment]
Thanks! This is helpful. Yeah, I've set 3.8 -> 3.7 manually and it seems to work, but not for `optimized_transducer`. I will try to fix cmake first and see if there is still the same issue.
