### ISSUE TITLE
import kaldilm

### ISSUE THREAD

**Issue by yuzhang112** [csukuangfj/kaldilm#4]
>>> import kaldilm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\kaldilm\__init__.py", line 1, in <module>
    from .arpa2fst import arpa2fst
  File "C:\Anaconda3\lib\site-packages\kaldilm\arpa2fst.py", line 3, in <module>
    import _kaldilm
ModuleNotFoundError: No module named '_kaldilm'

**Comment by csukuangfj** [comment]
> >>> import kaldilm
> 
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
>   File "C:\Anaconda3\lib\site-packages\kaldilm\__init__.py", line 1, in <module>
> 
>     from .arpa2fst import arpa2fst
> 
>   File "C:\Anaconda3\lib\site-packages\kaldilm\arpa2fst.py", line 3, in <module>
> 
>     import _kaldilm
> 
> ModuleNotFoundError: No module named '_kaldilm'

Could you see #1？ Let me know if it does not help.

**Comment by csukuangfj** [comment]
@yuzhang112 
Please refer to the README.md for how to install kaldilm using conda.
