### ISSUE TITLE
No module named '_kaldilm'

### ISSUE THREAD

**Issue by aarora8** [csukuangfj/kaldilm#5]
Hello,

Similar to issue #1, I'm trying to use kaldilm. I create a Conda env with python3.8  and installed kaldilm 1.3 with `pip install kaldilm`.

However, while using apra2fst function I got the error `ModuleNotFoundError: No module named '_kaldilm'`.

I do ont have `_kaldilm.cpython-38-x86_64-linux-gnu.so` or  `libfst.so libfst.so.16 libkaldilm_core.so` in the `/home/aarora/miniconda3/envs/k2/lib/python3.8/site-package`.

I got got it working at one server but not at another server. I tried copying these .so files and running `python setup.py bdist_wheel` but I did not work for me.

My log location from `pip install -v --no-cache-dir kaldilm` is as follows:

https://github.com/aarora8/snowfall/blob/safet-coe/egs/safet/asr/simple_v1/local2/log_files/install_kaldilm.log#L293

Can you please help me with this issue.

**Comment by csukuangfj** [comment]
@aarora8 
As you're using conda to install kaldilm, could you try
```
conda install -c k2-fsa -c conda-forge kaldilm
```

It should fix your problem.

I just updated the README.md to mention how to install kaldilm with conda.

**Comment by csukuangfj** [comment]
As for your error, I think your GCC is too old (4.8.5). Updating GCC to at least 5.x should fix the error when using `pip install kaldilm`.

**Comment by aarora8** [comment]
Thank you so much. It is working well with `conda install -c k2-fsa -c conda-forge kaldilm`.
